# Generated by Django 3.1.6 on 2021-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210411_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('    ', '     '), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Clothes', 'Clothes')], max_length=100),
        ),
    ]
