# Generated by Django 3.1.6 on 2021-04-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210411_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='auctions.category'),
        ),
    ]
