# Generated by Django 3.1.6 on 2021-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210411_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes')], max_length=100),
        ),
    ]
